#!/usr/bin/env python3
"""Download the web fonts the site uses and write a local @font-face sheet.

    python3 tools/fetch-fonts.py

Google Fonts is unreliable for a large share of visitors inside Iran, and a
font that never arrives takes the whole typographic identity with it. This
pulls the woff2 files once so the site serves them from its own domain.

Only the subsets the site actually sets are kept: Arabic and Latin for the
Persian body face, Latin for the display face used on Latin runs and figures.

Writes site/assets/fonts/*.woff2 and site/css/fonts.css.
"""
import os
import re
import sys
import urllib.request

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FONT_DIR = os.path.join(HERE, 'site', 'assets', 'fonts')
CSS_OUT = os.path.join(HERE, 'site', 'css', 'fonts.css')

API = ('https://fonts.googleapis.com/css2'
       '?family=Vazirmatn:wght@300;400;500;600'
       '&family=Cormorant+Garamond:wght@300;400;500;600'
       '&display=swap')

# Google only serves woff2 to a modern UA; anything else gets legacy formats.
UA = ('Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 '
      '(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36')

KEEP = {'Vazirmatn': {'arabic', 'latin'},
        'Cormorant Garamond': {'latin'}}


def get(url, binary=False):
    req = urllib.request.Request(url, headers={'User-Agent': UA})
    with urllib.request.urlopen(req, timeout=60) as r:
        data = r.read()
    return data if binary else data.decode('utf-8')


def main():
    os.makedirs(FONT_DIR, exist_ok=True)
    css = get(API)

    # Each @font-face is preceded by a /* subset */ comment.
    blocks = re.findall(r'/\*\s*([\w-]+)\s*\*/\s*(@font-face\s*\{.*?\})', css, re.S)
    if not blocks:
        sys.exit('no @font-face blocks returned — check the API url')

    out, kept, seen = [], 0, {}
    for subset, block in blocks:
        family = re.search(r"font-family:\s*'([^']+)'", block).group(1)
        if subset not in KEEP.get(family, set()):
            continue
        weight = re.search(r'font-weight:\s*(\d+)', block).group(1)
        style = re.search(r'font-style:\s*(\w+)', block).group(1)
        url = re.search(r'url\((https://[^)]+)\)', block).group(1)

        slug = family.lower().replace(' ', '-')
        name = f'{slug}-{weight}-{style}-{subset}.woff2'
        path = os.path.join(FONT_DIR, name)
        if url not in seen:
            open(path, 'wb').write(get(url, binary=True))
            seen[url] = name
            print(f'  {name}  {os.path.getsize(path) // 1024} KB')
        block = block.replace(url, '../assets/fonts/' + seen[url])
        # swap keeps text visible while the file arrives, rather than blank
        if 'font-display' not in block:
            block = block.replace('@font-face {', '@font-face {\n  font-display: swap;')
        out.append(f'/* {family} {weight} {style} — {subset} */\n{block}')
        kept += 1

    header = ('/* Generated by tools/fetch-fonts.py — do not edit by hand.\n'
              '   Self-hosted so the page keeps its typography where Google\n'
              '   Fonts does not reach. */\n\n')
    open(CSS_OUT, 'w', encoding='utf-8').write(header + '\n\n'.join(out) + '\n')
    print(f'\n{kept} faces -> site/css/fonts.css')


if __name__ == '__main__':
    main()
